module.exports = [
    {
      name: "business one",
      address: "1 somestreet Rd, Swamp lane",
      website: "swampyness.swamp",
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmFyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      description: "a great business doing something special",
      categories: "bar",
      discount: 0.15,
    },
    {
      name: "Melbourne Bernese",
      address: "some place in the hills",
      website: "melbournebernese.com.au",
      image: "https://melbournebernese.com.au/wp-content/uploads/2020/05/Lilly-close-up-1024x580.jpg",
      description: "Pets are family",
      categories: "pets",
      discount: 0.10,
    },
    {
      name: "Sooki Lounge",
      address: "1648 Burwood Hwy, Belgrave, VIC 3160",
      website: "sookilounge.com.au",
      image: "https://images.unsplash.com/photo-1614999098814-23c48ffa512d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bGl2ZSUyMG11c2ljfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      description: "best live music venue around!",
      categories: "Live music, bar",
      discount: 0.10,
    },
    {
      name: "business two",
      address: "1 somestreet Rd, Swamp lane",
      website: "swampyness.swamp",
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmFyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      description: "a business description",
      categories: "bar",
      discount: 0.05,
    },
    {
      name: "Melbourne Bernese",
      address: "some place in the hills",
      website: "melbournebernese.com.au",
      image: "https://melbournebernese.com.au/wp-content/uploads/2020/05/three-blind-mice-1024x580.jpg",
      description: "Pets are family",
      categories: "pets",
      discount: 0.10,
    },
    {
      name: "Sooki Lounge",
      address: "1648 Burwood Hwy, Belgrave, VIC 3160",
      website: "sookilounge.com.au",
      image: "https://images.unsplash.com/photo-1614999098814-23c48ffa512d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bGl2ZSUyMG11c2ljfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      description: "best live music venue around!",
      categories: "Live music, bar",
      discount: 0.10,
    },
]